SINGLE_SHOP = '{
  "shop_id": 1,
  "user_id": 1,
  "shop_name": "string",
  "create_date": 0,
  "title": "string",
  "announcement": "string",
  "currency_code": "string",
  "is_vacation": true,
  "vacation_message": "string",
  "sale_message": "string",
  "digital_sale_message": "string",
  "update_date": 0,
  "listing_active_count": 0,
  "digital_listing_count": 0,
  "login_name": "string",
  "accepts_custom_requests": true,
  "policy_welcome": "string",
  "policy_payment": "string",
  "policy_shipping": "string",
  "policy_refunds": "string",
  "policy_additional": "string",
  "policy_seller_info": "string",
  "policy_update_date": 0,
  "policy_has_private_receipt_info": true,
  "has_unstructured_policies": true,
  "policy_privacy": "string",
  "vacation_autoreply": "string",
  "url": "string",
  "image_url_760x100": "string",
  "num_favorers": 0,
  "languages": [
    "string"
  ],
  "icon_url_fullxfull": "string",
  "is_using_structured_policies": true,
  "has_onboarded_structured_policies": true,
  "include_dispute_form_link": true,
  "is_direct_checkout_onboarded": true,
  "is_calculated_eligible": true,
  "is_opted_in_to_buyer_promise": true,
  "is_shop_us_based": true,
  "transaction_sold_count": 0,
  "shipping_from_country_iso": "string",
  "shop_location_country_iso": "string",
  "review_count": 0,
  "review_average": 0
}'

MULTIPLE_SHOPS = '{
  "count": 2,
  "results": [
    {
      "shop_id": 1,
      "user_id": 1,
      "shop_name": "string",
      "create_date": 0,
      "title": "string",
      "announcement": "string",
      "currency_code": "string",
      "is_vacation": true,
      "vacation_message": "string",
      "sale_message": "string",
      "digital_sale_message": "string",
      "update_date": 0,
      "listing_active_count": 0,
      "digital_listing_count": 0,
      "login_name": "string",
      "accepts_custom_requests": true,
      "policy_welcome": "string",
      "policy_payment": "string",
      "policy_shipping": "string",
      "policy_refunds": "string",
      "policy_additional": "string",
      "policy_seller_info": "string",
      "policy_update_date": 0,
      "policy_has_private_receipt_info": true,
      "has_unstructured_policies": true,
      "policy_privacy": "string",
      "vacation_autoreply": "string",
      "url": "string",
      "image_url_760x100": "string",
      "num_favorers": 0,
      "languages": [
        "string"
      ],
      "icon_url_fullxfull": "string",
      "is_using_structured_policies": true,
      "has_onboarded_structured_policies": true,
      "include_dispute_form_link": true,
      "is_direct_checkout_onboarded": true,
      "is_calculated_eligible": true,
      "is_opted_in_to_buyer_promise": true,
      "is_shop_us_based": true,
      "transaction_sold_count": 0,
      "shipping_from_country_iso": "string",
      "shop_location_country_iso": "string",
      "review_count": 0,
      "review_average": 0
    },
    {
      "shop_id": 1,
      "user_id": 1,
      "shop_name": "string",
      "create_date": 0,
      "title": "string",
      "announcement": "string",
      "currency_code": "string",
      "is_vacation": true,
      "vacation_message": "string",
      "sale_message": "string",
      "digital_sale_message": "string",
      "update_date": 0,
      "listing_active_count": 0,
      "digital_listing_count": 0,
      "login_name": "string",
      "accepts_custom_requests": true,
      "policy_welcome": "string",
      "policy_payment": "string",
      "policy_shipping": "string",
      "policy_refunds": "string",
      "policy_additional": "string",
      "policy_seller_info": "string",
      "policy_update_date": 0,
      "policy_has_private_receipt_info": true,
      "has_unstructured_policies": true,
      "policy_privacy": "string",
      "vacation_autoreply": "string",
      "url": "string",
      "image_url_760x100": "string",
      "num_favorers": 0,
      "languages": [
        "string"
      ],
      "icon_url_fullxfull": "string",
      "is_using_structured_policies": true,
      "has_onboarded_structured_policies": true,
      "include_dispute_form_link": true,
      "is_direct_checkout_onboarded": true,
      "is_calculated_eligible": true,
      "is_opted_in_to_buyer_promise": true,
      "is_shop_us_based": true,
      "transaction_sold_count": 0,
      "shipping_from_country_iso": "string",
      "shop_location_country_iso": "string",
      "review_count": 0,
      "review_average": 0
    }
  ]
}'